version: '3'
services:

  postgres:
    image: "postgres:latest"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "postgres"

  simple-crud:
    build:
      context: ./../../
      dockerfile: ./Dockerfile
    restart: always
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    deploy:
      mode: replicated
      replicas: 1
